### ISSUE TITLE
German server IP is not in Germany

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdGuardVPNForiOS#11] opened 2020-10-22 10:52 UTC
I'm connected to the German (Frankfurt) server. However, ipleak.net shows my IP in London and France and I'm also seeing ads from Amazon Prime France on Twitter.￼
![image](https://user-images.githubusercontent.com/4127356/96862210-73ae7e80-1465-11eb-829b-f5330588c626.png)

**Comment by zzebrum** [comment] 2020-10-26 13:52
@iDjay yep, we are aware that some endpoints have the problem, it will be fixed soon!

**Comment by iDjay** [comment] 2020-11-03 22:30
@zzebrum when do you think it'll be fixed?

**Comment by ameshkov** [comment] 2020-11-04 10:49
Weird, we're using two different hosting provs, and MaxMind still fails to detect the country properly for both of them.

I guess we should simply report this to MaxMind and wait for this to be resolved on their side (as everyone is using their GeoIP database anyway).

**Comment by iDjay** [comment] 2020-11-05 12:05
@ameshkov also the server is still pretty slow with a maximum speed of 16mbit's.

**Comment by ameshkov** [comment] 2020-11-05 12:45
Yeah, we're testing a new hosting provider in Germany, and we're not too happy with the results so far.

**Comment by iDjay** [comment] 2020-11-09 13:09
Can you re-open it until it's fixed? Don't want to check every day :)

**Comment by iDjay** [comment] 2020-11-10 11:52
Fixed. However still pretty slow, 50 mbit's only :(

**Comment by iDjay** [comment] 2020-11-11 10:23
Now the IP is blocked by google @zzebrum @ameshkov

**Comment by iDjay** [comment] 2020-12-16 09:48
DNS is still not in Germany which blocks access to a few apps.

**Comment by ameshkov** [comment] 2020-12-16 19:30
There're two german locations now btw

**Comment by iDjay** [comment] 2020-12-16 20:02
Both having the issue :(

**Comment by ameshkov** [comment] 2020-12-17 20:11
Weird, I cannot reproduce this.

Please note, that different websites may use old IPs databases and this may lead to inconsistent results.
The best way to check the current state of an IP address is to use maxmind.com

**Comment by iDjay** [comment] 2020-12-17 20:48
@ameshkov did you try https://ipleak.net/ ? NordVPN recommended it to me before I switched to AdGuard VPN.

**Comment by ameshkov** [comment] 2020-12-17 20:54
They may very well have old IP databases, it's natural that websites need time to keep up with the changes to IP registry.

In the end, they all use MaxMind's database, the question is only how often they update it.

**Closed** 2021-02-16 07:34 UTC
Labels: Question, Resolution: Fixed, Status: Closed, Wontfix

**Comment by iDjay** [comment] 2021-02-16 10:28
@ameshkov

**Comment by ameshkov** [comment] 2021-02-16 10:32
Well, all our servers' IPs are properly registered in the MaxMind database, that's the only thing we can do from our side.

**Comment by iDjay** [comment] 2021-02-16 13:49
@ameshkov I tried every DNS server option now and it doesn't make any difference. So yes, sorry, you were right. DNS is not causing the issue, I guess it's the VPN connection detection.
